changelog:
  categories:
    - title: "Fixes"
      labels:
        - "bug"
    - title: "Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "Documentation"
      labels:
        - "documentation"
    - title: "Improvements"
      labels:
        - "improvement"
        - "performance"
        - "refactor"
    - title: "Breaking Changes"
      labels:
        - "breaking"
        - "breaking change"
        - "breaking changes"
    - title: "Deprecations"
      labels:
        - "deprecation"
        - "deprecate"
    - title: "Security"
      labels:
        - "security"

name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      tags: ${{ github.ref_name }}
