version: '3'
services:
  subconv:
    image: ghcr.io/bowencool/subconv:latest
    container_name: subconv
    restart: unless-stopped
    ports:
      - "48080:48080"
    volumes:
      - ./config.yaml:/app/config.yaml
