name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  packages: write
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag
        id: set_tag
        run: |
          echo "tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT

  build-image:
    needs: setup
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      tags: ${{ needs.setup.outputs.tag }},latest

  release:
    needs: [build-image]
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
